### ISSUE TITLE
future plans

### ISSUE THREAD

**Issue by berndhahnebach** [g7/sailfishx-patcher-f5321#15]
I would like to buy a new phone and for sure Sailfish will run on it!

Do you have any plans to update to newer versions of Xperia compact like this one?

Sony Xperia XZ2 Compact Smartphone

or would this just not possible with current sailfish images?

cheers bernd

**Comment by henning-schild** [comment]
XZ2 is not supported by sailfish itself, so that is probably not going to happen

I also thought about a new one some day. IMHO the only sane choice would be an Xperia 10 or XA2

A compact would be really nice, but those simply are not available anymore. And honestly this repo is a handy hack to still get support for a compact, but when buying a new one you might want to take a big one that is officially supported.

10 and XA2 have the recent android support, and that is probably what you want for a new one

**Comment by henning-schild** [comment]
I am just a user myself but would suggest you close the issue. It has nothing to do with this repo and you should ask your questions somewhere else.

**Comment by berndhahnebach** [comment]
thanks for your informations. I have been owning an Xperia X for two years. But it is totally brocken the time beeing and I surely need a new one. Even it it is a hack I will give it a try. I like the small phones. Still have two N9 around which are so cute. Thus I ordered a Xperia X compact. Since they are three years old already they are just some bucks. 

XA2 and 10 are tablets not phones IMHO.

cheers bernd
