### ISSUE TITLE
about jolla account

### ISSUE THREAD

**Issue by gongxuelei66** [g7/sailfishx-patcher-f5321#5]
hello，@g7 ，I have flashed the  community version of sailfish os for xc， and login my jolla account，and after it，I flashed 3.0.0.8 version which was built in your way（with g7 patch）,，I login my jolla account but in my account’s devices，it displays f5321 not f5121，and I can't find Android surport in Jolla shop. I want to know if it is normal that display f5321 in my account？if not how to solve it? And I try to build a package for xc with sfos2.1 in Windows,and it seems not work,please help me ,thank you

**Comment by g7** [comment]
Hello @gongxuelei66!

If you have used the community version, the IMEI on Jolla's side will remain attached to the 'f5321' device. But that's not an issue as long as you have an unused Sailfish X license.

If you can't install Android Support that's probably because the Sailfish X license has been already used.

**Comment by gongxuelei66** [comment]
Thank you @g7, I thought Jolla would recognize the f5121 to allow the phone use the sailfish x license😂, and I try to change the f5121 to f5321,but there is no way.and are there any differences between xc and x？ Are there any questions not be solved?
