### ISSUE TITLE
whatsapp text input bar is overlapped keyboard

### ISSUE THREAD

**Issue by henning-schild** [g7/sailfishx-patcher-f5321#9]
I recently started seeing the virtual keyboard overlapping the input bar of the android app whatsapp. Not sure when it started but it is present with 3.0.3.10 and wa 2.19.173

That might be specific to the f5321 since it has a smaller screen (also a lower resolution?)

Workaround is to type "blind" and pull down the keyboard to look at the outcome, or to type in landscape

**Comment by g7** [comment]
Hello,

Does this still happen?

**Comment by henning-schild** [comment]
yes, telegram is affected as well but there i have depecher as native alternative. I guess any android app has too much keyboard overlap ... already played with changing some values in the keyboard qmls but without success

I remember a pure OSS image did not have the word suggestions, but also no android. No clue ...

**Comment by henning-schild** [comment]
Can anyone reproduce the issue, or is it maybe specific to my installation? My guess is that the smaller screen of the compact might be the root cause ... not sure whether the resolution is actually different

**Comment by g7** [comment]
Does this still happen with 3.3 Rokua? To be fair on my X Compact I never experienced something similar (since 2.1.3). Running WhatsApp 2.19.362 installed from an .apk downloaded from the official website.

**Comment by henning-schild** [comment]
Yes, the app version does not seem to matter much. I have 2.2.0.141 now, on 3.3. As i said, other android apps are affected as well. It used to work, and "broke". Maybe with Oulanka or Hossa.

Did not try a reflash.

Might be off-topic ... what do i risk loosing if i patch the latest firmware, flash it again and apply one of the sailfish backups? If the will just get be back to full operation i might want to do that, also to use the new encryption feature.

**Comment by g7** [comment]
Although I didn't try Sailfish Backups since a long while AFAIK it doesn't backup everything and you'll lose some data (especially 3rd-party app data).

You may try first to remove and re-install the Android Support. Please note that this will remove every android data (apps and stored data). If you want to go this route you can remove the Android Support from the Jolla Store, reboot and then reinstall it again.

But now I'm thinking about something... did you by any chance have installed "Aliendalvik control" from openrepos and used it to disable the navigation bar? I can reproduce your issue by disabling the navigation bar on android apps.

To enable encryption I have copied the entire content of the home LVM LV with dd, enabled encryption, then synced back the content via rsync.

**Comment by henning-schild** [comment]
Oh ... yes i did have it. And i was wondering why i got stuck in android apps without a way back sometimes ... it was the bar that i did not switch off intentionally! Thank you so much!
